"""create market events table

Revision ID: 86d6bb4f5beb
Revises: 
Create Date: 2026-08-11 23:20:54.368493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d6bb4f5beb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_market_events_symbol'), 'market_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_events_timestamp'), 'market_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_events_timestamp'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_symbol'), table_name='market_events')
    op.drop_table('market_events')
    # ### end Alembic commands ###
